version: "2017-09-20"
allow_concurrent_steps: true

pipeline:
- id: build-spilo-cdp
  env:
    BASE_IMAGE: container-registry.zalando.net/library/ubuntu-22.04
    PGVERSION: 15
    SPILO_TEST_IMAGE: test-spilo-cdp
    MULTI_ARCH_REGISTRY: container-registry-test.zalando.net/acid
    TRIGGER_REGISTRY: registry-write.opensource.zalan.do/acid
  type: script
  when:
    - event: push
      branch: master
    - event: pull_request
  timeout: 3h
  vm_config:
    type: linux
    size: extra_large
  commands:
  - desc: Build test image
    cmd: |
      chmod -R o-w postgres-appliance
      cd postgres-appliance
      docker build --build-arg PGVERSION="$PGVERSION" \
                   --build-arg BASE_IMAGE="$BASE_IMAGE" \
                   -t "$SPILO_TEST_IMAGE" .
      docker images
  - desc: Test spilo image
    cmd: |
      sudo apt-get update
      sudo apt-get install -y python3-pip
      sudo pip3 install docker-compose==1.17.1
      bash postgres-appliance/tests/test_spilo.sh
  - desc: Tag and push spilo-cdp docker images
    cmd: |
      # push docker images only for commits to the master branch
      if [ -z "$CDP_SOURCE_BRANCH" ]; then
          cd postgres-appliance

          PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[0-9]*\).*$/\1/p' Dockerfile)
          IMAGE_SUFFIX="cdp-$PGVERSION:$PATRONIVERSION-p$CDP_TARGET_BRANCH_COUNTER"

          # container-registry

          # create a Buildkit builder with CDP specific configuration
          docker buildx create --config /etc/cdp-buildkitd.toml --driver-opt network=host --bootstrap --use

          ECR_TEST_IMAGE="$MULTI_ARCH_REGISTRY/spilo-$IMAGE_SUFFIX"
          docker buildx build --platform "linux/amd64,linux/arm64" \
                              --build-arg PGVERSION="$PGVERSION" \
                              --build-arg BASE_IMAGE="$BASE_IMAGE" \
                              -t "$ECR_TEST_IMAGE" \
                              --network=host \
                              --push .
          cdp-promote-image "$ECR_TEST_IMAGE"

          # opensource.zalan.do (trigger image)
          docker pull --platform linux/amd64 "$ECR_TEST_IMAGE"
          TRIGGER_IMAGE="$TRIGGER_REGISTRY/spilo-$IMAGE_SUFFIX"
          docker tag "$ECR_TEST_IMAGE" "$TRIGGER_IMAGE"
          docker images
          docker push "$TRIGGER_IMAGE"
      fi
- id: tag-spilo
  depends_on: [build-spilo-cdp]
  type: script
  requires_human_approval: true
  when:
    event: push
    branch: master
  commands:
  - desc: Tag release spilo image
    cmd: |
      PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[0-9]*\).*$/\1/p' postgres-appliance/Dockerfile)
      COUNTER=$(git tag | sed -n "s/^$PATRONIVERSION-p//p" | sort -un | tail -n1)
      TAG="$PATRONIVERSION-p$((COUNTER+1))"

      git gh-tag "$TAG"
